name: vm-solutions-mateus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 0' #Domingo
    - cron: '0 10 * * 1' #Segunda-Feira
    - cron: '0 10 * * 2' #Terça-Feira
    - cron: '0 10 * * 3' #Quarta - Feira
    - cron: '0 10 * * 4' #Quinta - Feira
    - cron: '0 10 * * 5' #Sexta-Feira
    - cron: '0 10 * * 6' #Sábado 

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    strategy:
      matrix:
        scripts:
          - assai.py
          - atacadao.py 
          - novoatacarejo.py
          - frangolandia.py
          - cometa.py
          - atakarejo.py
          - gbarbosa.py

    steps:
      - name: Checkout (repo atual)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          lfs: true
          submodules: recursive

      - name: Ajustes Git no Windows (opcional)
        shell: pwsh
        run: |
          git config --global user.name "user"
          git config --global user.email "usermail10@gmail.com"
          git config --global core.longpaths true

      - name: Checkout de outro repositório
        uses: actions/checkout@v4
        with:
          repository: solutionsmateus/supermercados-code
          ref: main
          path: supermercados-code

      - name: Setup Python 3.12 (com cache pip)
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: supermercados-code/requirements.txt

      - name: Instalar dependências (se existir requirements.txt)
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "supermercados-code/requirements.txt") {
            pip install -r supermercados-code/requirements.txt
          }

      - name: Criar pasta Encartes
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path Encartes | Out-Null

      - name: Executar scripts em matrix
        shell: pwsh
        working-directory: supermercados-code
        run: |
          python "${{ matrix.script }}"

      # (Opcional) Baixar tudo que foi gerado na pasta Encartes
      - name: Upload arquivos gerados
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: encartes-${{ github.run_id }}
          path: Encartes/**

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Placeholder de deploy
        run: echo "Implemente seu deploy aqui"
